### ISSUE TITLE
Crash on entering the StatusHud config screen

### ISSUE THREAD

**Issue by kamild1996** [BoogieMonster1O1/StatusHud#1]
Hopefully the crash log includes everything you need, otherwise please let me know. Minecraft 1.16.1.
[crash-2020-08-26_16.44.13-client.txt](https://github.com/BoogieMonster1O1/StatusHud/files/5130551/crash-2020-08-26_16.44.13-client.txt)

**Comment by BoogieMonster1O1** [comment]
StatusHud 1.1.0 only supports 1.16.2. I’ll probably release a backport to 1.16.1 soon. For now, use 1.0.1.
